# Generated by Django 3.1.3 on 2021-05-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_count', models.IntegerField()),
                ('following_count', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
            ],
        ),
    ]
