# Generated by Django 3.2.3 on 2021-05-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bio',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='city',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='city',
            field=models.ManyToManyField(to='main.Cities'),
        ),
    ]
